### PR TITLE
Make sure smhi provider api only gets a maximimum of 6 digits coordinates

### LINKED ISSUE #2955: SMHI isn't working with the weather module
## I found a bug in MagicMirror

Please make sure to only submit reproducible issues. You can safely remove everything above the dividing line.
When submitting a new issue, please supply the following information:

**Platform**: Raspberry Pi 4 4GB 

**Node Version**: 17.8.0 

**MagicMirror² Version**: 2.21.0

**Description**: I am unable to use SMHI in the weather integration. The module just get stuck in "loading" and nothing happens. I tried to use Openweathermap as a provider and that worked without any issues.

**Steps to Reproduce**: Use SMHI as a weather provider. 

**Expected Results**: Current weather when I use SMHI.

**Actual Results**: The module get stuck at loading

**Configuration**: [config.txt](https://github.com/MichMich/MagicMirror/files/9833854/config.txt)

### PR DESCRIPTION
**Pull request by rejas**
Fixes #2955

### CODE REVIEW

**Comment by rejas** [comment]
Although the original issue got closed since it was unrelated to this PR, it should still get merged. The API doesnt like 6 digit lat/lon:
https://opendata-download-metfcst.smhi.se/api/category/pmp3g/version/2/geotype/point/lon/15.12345678/lat/56.12345678/data.json

Shorting the lat/lon parameters works like expected:
https://opendata-download-metfcst.smhi.se/api/category/pmp3g/version/2/geotype/point/lon/15.123456/lat/56.123456/data.json

File: modules/default/weather/providers/smhi.js [hunk 1]
```diff
@@ -104,8 +104,12 @@ WeatherProvider.register("smhi", {
 	 * @returns {string} the url for the specified coordinates
 	 */
 	getURL() {
-		let lon = this.config.lon;
-		let lat = this.config.lat;
+		const formatter = new Intl.NumberFormat("en-US", {
+			minimumFractionDigits: 2,
+			maximumFractionDigits: 2
```
Comment (khassel) [inline modules/default/weather/providers/smhi.js:109]: did not dig in the docs of NumberFormat but would expect `6` instead of `2` as written in the comments above (?)

Comment (rejas) [reply modules/default/weather/providers/smhi.js]: Yeah, i shouldnt code while having a cold :-( Fixed!
